const client = require('../index');
const chatModel = require('../models/chatGSchema')
const config = require('../config.json');

async function Punish(message, GuardType, Embed) {
    let result = false;
    const Database = await chatModel.findOne({ ServerID: message.guild.id });
    const LogChannel = message.guild.channels.cache.find(channel => channel.id === config.ChatGuard.logchannel);
    let TimeoutDuration = Database.MuteDurationMinute;

    if(Date.now() < message.member.communicationDisabledUntilTimestamp) return;
    if(Database.MuteDurationMinute < 1)TimeoutDuration = 60;
    const CanBeMuted = message.guild.me.permissions.has('MODERATE_MEMBERS');
    const CanBeLog = LogChannel && LogChannel.type === 'GUILD_TEXT';

    if (!CanBeMuted) return console.log('WARN - The operation failed.  Reason: I don\'t have "MODERATE_MEMBERS" permission');
    if(!CanBeLog) return console.log('WARN - The operation failed.  Reason: Searched logchannel was not found');
    if(Database.BlueListMembers.includes(message.member.id) === true)result = true;
    if(result === true) {

        await chatModel.findOneAndUpdate({ ServerID: message.guild.id }, { $pull: { BlueListMembers: message.member.id }});
        await chatModel.findOneAndUpdate({ ServerID: message.guild.id }, { $push: { BlackListMembers: message.member.id } }, { upsert: true });
        
        message.member.timeout(TimeoutDuration * 1000 * 60, 'chatGuard');
     
        setTimeout(async() => { 
            await chatModel.findOneAndUpdate({ ServerID: message.guild.id }, { $pull: { BlackListMembers: message.member.id } });
            if(message.member.isCommunicationDisabled()) message.member.timeout(null, 'chatGuard').catch(() => {}); }, TimeoutDuration * 1000 * 60 ); 

        if(GuardType === 'CharacterLimit') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Aşırı karakter kullandığın için **'+TimeoutDuration+'** Dakika Mute yedin. Lütfen kurallara uymaya özen göster')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Nickli kullanıcı '+message.content.length+' uzunluğunda mesaj yazdığı için **'+TimeoutDuration+'** Dakika boyunca mutelendi.')]}).catch(() => {});
        }
        if(GuardType === 'MassPingGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Aşırı etiket attığın için **'+TimeoutDuration+'** Dakika Mute yedin. Lütfen kurallara uymaya özen göster!')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Nickli kullanıcı mesajında **'+message.mentions.users.size+'** kişiyi etiketlediği için **'+TimeoutDuration+'** Dakika boyunca mutelendi.')]}).catch(() => {});
        }
        if(GuardType === 'InviteGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Sunucu daveti attığın için **'+TimeoutDuration+'** Dakika Mute yedin. Lütfen kurallara uymaya özen göster')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Nickli kullanıcı **'+message.content+'** içerikli mesajında sunucu daveti bulunduğu için **'+TimeoutDuration+'** Dakika boyunca mutelendi.')]}).catch(() => {});
        }
        if(GuardType === 'SpamGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Spam yaptığın için **'+TimeoutDuration+'** Dakika Mute yedin. Lütfen kurallara uymaya özen göster')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, Nickli kullanıcı Spam yaptığı için **'+TimeoutDuration+'** Dakika boyunca mutelendi.')]}).catch(() => {});
        }
    }
    if(result === false) {

        await chatModel.findOneAndUpdate({ ServerID: message.guild.id }, { $push: { BlueListMembers: message.member.id } }, { upsert: true });
        setTimeout(async() => {
            await chatModel.findOneAndUpdate({ ServerID: message.guild.id }, { $pull: { BlueListMembers: message.member.id } }); 
        }, 7200000); 

        if(GuardType === 'CharacterLimit') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, You\'re not allowed to use extreme characters, so you\'ll be punished if you repeat it !')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, named user has received a warning because he wrote **'+message.content.length+'** chars like what OwO.')]}).catch(() => {});
        }
        if(GuardType === 'MassPingGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, You\'re not allowed to massping, you\'ll be fined if you repeat it !')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, named user has received a warning because he mentioned **'+message.mentions.users.size+'** users.')]}).catch(() => {});
        }
        if(GuardType === 'InviteGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, You are not allowed to send a Server Invitation; if it repetitions you will be punished !')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, named user has received a warning because he tried to include a server invitation in the message like **'+message.content+'**.')]}).catch(() => {});
        }
        if(GuardType === 'SpamGuard') {
            message.channel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>, You are not allowed to spam; if you do so, you will be punished !')]}).catch(() => {});
            return LogChannel.send({ embeds: [Embed.setDescription('<@'+message.author.id+'>,  named user has received a warning because he spammed.')]}).catch(() => {});
        }
    }
    return result;
}
  
async function WhiteList(message) {
    let result = false;
    const Database = await chatModel.findOne({ ServerID: message.guild.id });
    if (Database && Database.WhiteListMembers.includes(message.member.id) === true)result = true;
    if(Database && Database.WhiteListChannels.includes(message.channel.id) === true)result = true;
    let roles = message.member.roles.cache.map(role => role.id);
    if (roles.some(role => Database.WhiteListRoles.includes(role)))result = true;
    return result;
}

function BadWord(msgcontent) {
    let result = false;
    let array = ["ahole",
    "anus",
    "ash0le",
    "ash0les",
    "asholes",
    "ass",
    "Ass Monkey",
    "Assface",
    "assh0le",
    "assh0lez",
    "asshole",
    "assholes",
    "assholz",
    "asswipe",
    "azzhole",
    "bassterds",
    "bastard",
    "bastards",
    "bastardz",
    "basterds",
    "basterdz",
    "Biatch",
    "bitch",
    "bitches",
    "Blow Job",
    "boffing",
    "butthole",
    "buttwipe",
    "c0ck",
    "c0cks",
    "c0k",
    "Carpet Muncher",
    "cawk",
    "cawks",
    "Clit",
    "cnts",
    "cntz",
    "cock",
    "cockhead",
    "cock-head",
    "cocks",
    "CockSucker",
    "cock-sucker",
    "crap",
    "cum",
    "cunt",
    "cunts",
    "cuntz",
    "dick",
    "dild0",
    "dild0s",
    "dildo",
    "dildos",
    "dilld0",
    "dilld0s",
    "dominatricks",
    "dominatrics",
    "dominatrix",
    "dyke",
    "enema",
    "f u c k",
    "f u c k e r",
    "fag",
    "fag1t",
    "faget",
    "fagg1t",
    "faggit",
    "faggot",
    "fagg0t",
    "fagit",
    "fags",
    "fagz",
    "faig",
    "faigs",
    "fart",
    "flipping the bird",
    "fuck",
    "fucker",
    "fuckin",
    "fucking",
    "fucks",
    "Fudge Packer",
    "fuk",
    "Fukah",
    "Fuken",
    "fuker",
    "Fukin",
    "Fukk",
    "Fukkah",
    "Fukken",
    "Fukker",
    "Fukkin",
    "g00k",
    "God-damned",
    "h00r",
    "h0ar",
    "h0re",
    "hells",
    "hoar",
    "hoor",
    "hoore",
    "jackoff",
    "jap",
    "japs",
    "jerk-off",
    "jisim",
    "jiss",
    "jizm",
    "jizz",
    "knob",
    "knobs",
    "knobz",
    "kunt",
    "kunts",
    "kuntz",
    "Lezzian",
    "Lipshits",
    "Lipshitz",
    "masochist",
    "masokist",
    "massterbait",
    "masstrbait",
    "masstrbate",
    "masterbaiter",
    "masterbate",
    "masterbates",
    "Motha Fucker",
    "Motha Fuker",
    "Motha Fukkah",
    "Motha Fukker",
    "Mother Fucker",
    "Mother Fukah",
    "Mother Fuker",
    "Mother Fukkah",
    "Mother Fukker",
    "mother-fucker",
    "Mutha Fucker",
    "Mutha Fukah",
    "Mutha Fuker",
    "Mutha Fukkah",
    "Mutha Fukker",
    "n1gr",
    "nastt",
    "nigger;",
    "nigur;",
    "niiger;",
    "niigr;",
    "orafis",
    "orgasim;",
    "orgasm",
    "orgasum",
    "oriface",
    "orifice",
    "orifiss",
    "packi",
    "packie",
    "packy",
    "paki",
    "pakie",
    "paky",
    "pecker",
    "peeenus",
    "peeenusss",
    "peenus",
    "peinus",
    "pen1s",
    "penas",
    "penis",
    "penis-breath",
    "penus",
    "penuus",
    "Phuc",
    "Phuck",
    "Phuk",
    "Phuker",
    "Phukker",
    "polac",
    "polack",
    "polak",
    "Poonani",
    "pr1c",
    "pr1ck",
    "pr1k",
    "pusse",
    "pussee",
    "pussy",
    "puuke",
    "puuker",
    "qweir",
    "recktum",
    "rectum",
    "retard",
    "sadist",
    "scank",
    "schlong",
    "screwing",
    "semen",
    "sex",
    "sexy",
    "Sh!t",
    "sh1t",
    "sh1ter",
    "sh1ts",
    "sh1tter",
    "sh1tz",
    "shit",
    "shits",
    "shitter",
    "Shitty",
    "Shity",
    "shitz",
    "Shyt",
    "Shyte",
    "Shytty",
    "Shyty",
    "skanck",
    "skank",
    "skankee",
    "skankey",
    "skanks",
    "Skanky",
    "slag",
    "slut",
    "sluts",
    "Slutty",
    "slutz",
    "son-of-a-bitch",
    "tit",
    "turd",
    "va1jina",
    "vag1na",
    "vagiina",
    "vagina",
    "vaj1na",
    "vajina",
    "vullva",
    "vulva",
    "w0p",
    "wh00r",
    "wh0re",
    "whore",
    "xrated",
    "xxx",
    "b!+ch",
    "bitch",
    "blowjob",
    "clit",
    "arschloch",
    "fuck",
    "shit",
    "ass",
    "asshole",
    "b!tch",
    "b17ch",
    "b1tch",
    "bastard",
    "bi+ch",
    "boiolas",
    "buceta",
    "c0ck",
    "cawk",
    "chink",
    "cipa",
    "clits",
    "cock",
    "cum",
    "cunt",
    "dildo",
    "dirsa",
    "ejakulate",
    "fatass",
    "fcuk",
    "fuk",
    "fux0r",
    "hoer",
    "hore",
    "jism",
    "kawk",
    "l3itch",
    "l3i+ch",
    "masturbate",
    "masterbat*",
    "masterbat3",
    "motherfucker",
    "s.o.b.",
    "mofo",
    "nazi",
    "nigga",
    "nigger",
    "nutsack",
    "phuck",
    "pimpis",
    "pusse",
    "pussy",
    "scrotum",
    "sh!t",
    "shemale",
    "shi+",
    "sh!+",
    "slut",
    "smut",
    "teets",
    "tits",
    "boobs",
    "b00bs",
    "teez",
    "testical",
    "testicle",
    "titt",
    "w00se",
    "jackoff",
    "wank",
    "whoar",
    "whore",
    "*damn",
    "*dyke",
    "*fuck*",
    "*shit*",
    "@$$",
    "amcik",
    "andskota",
    "arse*",
    "assrammer",
    "ayir",
    "bi7ch",
    "bitch*",
    "bollock*",
    "breasts",
    "butt-pirate",
    "cabron",
    "cazzo",
    "chraa",
    "chuj",
    "Cock*",
    "cunt*",
    "d4mn",
    "daygo",
    "dego",
    "dick*",
    "dike*",
    "dupa",
    "dziwka",
    "ejackulate",
    "Ekrem*",
    "Ekto",
    "enculer",
    "faen",
    "fag*",
    "fanculo",
    "fanny",
    "feces",
    "feg",
    "Felcher",
    "ficken",
    "fitt*",
    "Flikker",
    "foreskin",
    "Fotze",
    "Fu(*",
    "fuk*",
    "futkretzn",
    "gook",
    "guiena",
    "h0r",
    "h4x0r",
    "hell",
    "helvete",
    "hoer*",
    "honkey",
    "Huevon",
    "hui",
    "injun",
    "jizz",
    "kanker*",
    "kike",
    "klootzak",
    "kraut",
    "knulle",
    "kuk",
    "kuksuger",
    "Kurac",
    "kurwa",
    "kusi*",
    "kyrpa*",
    "lesbo",
    "mamhoon",
    "masturbat*",
    "merd*",
    "mibun",
    "monkleigh",
    "mouliewop",
    "muie",
    "mulkku",
    "muschi",
    "nazis",
    "nepesaurio",
    "nigger*",
    "orospu",
    "paska*",
    "perse",
    "picka",
    "pierdol*",
    "pillu*",
    "pimmel",
    "piss*",
    "pizda",
    "poontsee",
    "poop",
    "porn",
    "p0rn",
    "pr0n",
    "preteen",
    "pula",
    "pule",
    "puta",
    "puto",
    "qahbeh",
    "queef*",
    "rautenberg",
    "schaffer",
    "scheiss*",
    "schlampe",
    "schmuck",
    "screw",
    "sh!t*",
    "sharmuta",
    "sharmute",
    "shipal",
    "shiz",
    "skribz",
    "skurwysyn",
    "sphencter",
    "spic",
    "spierdalaj",
    "splooge",
    "suka",
    "b00b*",
    "testicle*",
    "titt*",
    "twat",
    "vittu",
    "wank*",
    "wetback*",
    "wichser",
    "wop*",
    "yed",
    "zabourah",
    'allahoc',
    'allahoç',
    'allahamk',
    'allahaq',
    '0r0spuc0cu',
    '4n4n1 sk3r1m',
    'p1c',
    '@n@nı skrm',
    'orsb',
    'orsbcogu',
    'amnskm','anaskm',
    'oc',
    'abaza',
    'abazan',
    'ag',
    'a\u011fz\u0131na s\u0131\u00e7ay\u0131m',
    'fuck',
    'shit',
    'ahmak','seks','sex','allahs\u0131z','amar\u0131m','ambiti','am biti','amc\u0131\u011f\u0131','amc\u0131\u011f\u0131n','amc\u0131\u011f\u0131n\u0131','amc\u0131\u011f\u0131n\u0131z\u0131','amc\u0131k','amc\u0131k ho\u015faf\u0131','amc\u0131klama','amc\u0131kland\u0131','amcik','amck','amckl','amcklama','amcklaryla','amckta','amcktan','amcuk','am\u0131k','am\u0131na','amına','am\u0131nako','am\u0131na koy','am\u0131na koyar\u0131m',
    'am\u0131na koyay\u0131m',
    'am\u0131nakoyim',
    'am\u0131na koyyim',
    'am\u0131na s',
    'am\u0131na sikem',
    'am\u0131na sokam',
    'am\u0131n feryad\u0131',
    'am\u0131n\u0131',
    'am\u0131n\u0131 s',
    'am\u0131n oglu',
    'am\u0131no\u011flu',
    'am\u0131n o\u011flu','am\u0131s\u0131na','am\u0131s\u0131n\u0131','amina','amina g','amina k','aminako','aminakoyarim','amina koyarim','amina koyay\u0131m','amina koyayim','aminakoyim','aminda','amindan','amindayken','amini','aminiyarraaniskiim','aminoglu','amin oglu','amiyum','amk','amkafa','amk \u00e7ocu\u011fu','amlarnzn','aml\u0131','amm','ammak','ammna','amn','amna','amnda','amndaki','amngtn','amnn','amona','amq','ams\u0131z','amsiz','amsz','amteri','amugaa','amu\u011fa','amuna','ana','anaaann','anal','analarn','anam','anamla','anan','anana','anandan','anan\u0131','anan\u0131','anan\u0131n','anan\u0131n am','anan\u0131n am\u0131','anan\u0131n d\u00f6l\u00fc','anan\u0131nki','anan\u0131sikerim','anan\u0131 sikerim','anan\u0131sikeyim','anan\u0131 sikeyim','anan\u0131z\u0131n','anan\u0131z\u0131n am','anani','ananin','ananisikerim','anani sikerim','ananisikeyim','anani sikeyim','anann','ananz','anas','anas\u0131n\u0131','anas\u0131n\u0131n am','anas\u0131 orospu','anasi','anasinin','anay','anayin','angut','anneni','annenin','annesiz','anuna','aq','a.q','a.q.','aq.','ass','atkafas\u0131','atm\u0131k','att\u0131rd\u0131\u011f\u0131m','attrrm','auzlu','avrat','ayklarmalrmsikerim','azd\u0131m','azd\u0131r','azd\u0131r\u0131c\u0131','babaannesi ka\u015far','baban\u0131','baban\u0131n','babani','babas\u0131 pezevenk','baca\u011f\u0131na s\u0131\u00e7ay\u0131m','bac\u0131na','bac\u0131n\u0131','bac\u0131n\u0131n','bacini','bacn','bacndan','bacy','bastard','b\u0131z\u0131r','bitch','biting','boner','bosalmak','bo\u015falmak','cenabet','cibiliyetsiz','cibilliyetini','cibilliyetsiz','cif','cikar','cim','\u00e7\u00fck','dalaks\u0131z','dallama','daltassak','dalyarak','dalyarrak','dangalak','dassagi','diktim','dildo','dingil','dingilini','dinsiz','dkerim','domal','domalan','domald\u0131','domald\u0131n','domal\u0131k','domal\u0131yor','domalmak','domalm\u0131\u015f','domals\u0131n','domalt','domaltarak','domalt\u0131p','domalt\u0131r','domalt\u0131r\u0131m','domaltip','domaltmak','d\u00f6l\u00fc','d\u00f6nek','d\u00fcd\u00fck','eben','ebeni','ebenin','ebeninki','ebleh','ecdad\u0131n\u0131','ecdadini','embesil','emi','fahise','fahi\u015fe','feri\u015ftah','ferre','fuck','fucker','fuckin','fucking','gavad','gavat','giberim','giberler','gibis','gibi\u015f','gibmek','gibtiler','goddamn','godo\u015f','godumun','gotelek','gotlalesi','gotlu','gotten','gotundeki','gotunden','gotune','gotunu','gotveren','goyiim','goyum','goyuyim','goyyim','g\u00f6t','g\u00f6t deli\u011fi','g\u00f6telek','g\u00f6t herif','g\u00f6tlalesi','g\u00f6tlek','g\u00f6to\u011flan\u0131','g\u00f6t o\u011flan\u0131','g\u00f6to\u015f','g\u00f6tten','g\u00f6t\u00fc','g\u00f6t\u00fcn','g\u00f6t\u00fcne','g\u00f6t\u00fcnekoyim','g\u00f6t\u00fcne koyim','g\u00f6t\u00fcn\u00fc','g\u00f6tveren','g\u00f6t veren','g\u00f6t verir','gtelek','gtn','gtnde','gtnden','gtne','gtten','gtveren','hasiktir','hassikome','hassiktir','has siktir','hassittir','haysiyetsiz','hayvan herif','ho\u015faf\u0131','h\u00f6d\u00fck','hsktr','huur','\u0131bnel\u0131k','ibina','ibine','ibinenin','ibne','ibnedir','ibneleri','ibnelik','ibnelri','ibneni','ibnenin','ibnerator','ibnesi','idiot','idiyot','imansz','ipne','iserim','i\u015ferim','ito\u011flu it','kafam girsin','kafas\u0131z','kafasiz','kahpe','kahpenin','kahpenin feryad\u0131','kaka','kaltak','kanc\u0131k','kancik','kappe','karhane','ka\u015far','kavat','kavatn','kaypak','kayyum','kerane','kerhane','kerhanelerde','kevase','keva\u015fe','kevvase','koca g\u00f6t','kodu\u011fmun','kodu\u011fmunun','kodumun','kodumunun','koduumun','koyarm','koyay\u0131m','koyiim','koyiiym','koyim','koyum','koyyim','krar','kukudaym','laciye boyad\u0131m','libo\u015f','madafaka','malafat','malak','mcik','memelerini','mezveleli','minaamc\u0131k','mincikliyim','mna','monakkoluyum','motherfucker','mudik','oc','ocuu','ocuun','O\u00c7','o\u00e7','o. \u00e7ocu\u011fu','o\u011flan','o\u011flanc\u0131','o\u011flu it','orosbucocuu','orospu','orospucocugu','orospu cocugu','orospu \u00e7oc','orospu\u00e7ocu\u011fu','orospu \u00e7ocu\u011fu','orospu \u00e7ocu\u011fudur','orospu \u00e7ocuklar\u0131','orospudur','orospular','orospunun','orospunun evlad\u0131','orospuydu','orospuyuz','orostoban','orostopol','orrospu','oruspu','oruspu\u00e7ocu\u011fu','oruspu \u00e7ocu\u011fu','osbir','ossurduum','ossurmak','ossuruk','osur','osurduu','osuruk','osururum','otuzbir','\u00f6k\u00fcz','\u00f6\u015fex','patlak zar','penis','pezevek','pezeven','pezeveng','pezevengi','pezevengin evlad\u0131','pezevenk','pezo','pic','pici','picler','pi\u00e7','pi\u00e7in o\u011flu','pi\u00e7 kurusu','pi\u00e7ler','pipi','pipi\u015f','pisliktir','porno','pussy','pu\u015ft','pu\u015fttur','rahminde','revizyonist','s1kerim','s1kerm','s1krm','sakso','saksofon','saxo','sekis','serefsiz','sevgi koyar\u0131m','sevi\u015felim','sexs','s\u0131\u00e7ar\u0131m','s\u0131\u00e7t\u0131\u011f\u0131m','s\u0131ecem','sicarsin','sie','sik','sikdi','sikdi\u011fim','sike','sikecem','sikem','siken','sikenin','siker','sikerim','sikerler','sikersin','sikertir','sikertmek','sikesen','sikesicenin','sikey','sikeydim','sikeyim','sikeym','siki','sikicem','sikici','sikien','sikienler','sikiiim','sikiiimmm','sikiim','sikiir','sikiirken','sikik','sikil','sikildiini','sikilesice','sikilmi','sikilmie','sikilmis','sikilmi\u015f','sikilsin','sikim','sikimde','sikimden','sikime','sikimi','sikimiin','sikimin','sikimle','sikimsonik','sikimtrak','sikin','sikinde','sikinden','sikine','sikini','sikip','sikis','sikisek','sikisen','sikish','sikismis','siki\u015f','siki\u015fen','siki\u015fme','sikitiin','sikiyim','sikiym','sikiyorum','sikkim','sikko','sikleri','sikleriii','sikli','sikm','sikmek','sikmem','sikmiler','sikmisligim','siksem','sikseydin','sikseyidin','siksin','siksinbaya','siksinler','siksiz','siksok','siksz','sikt','sikti','siktigimin','siktigiminin','sikti\u011fim','sikti\u011fimin','sikti\u011fiminin','siktii','siktiim','siktiimin','siktiiminin','siktiler','siktim','siktim','siktimin','siktiminin','siktir','siktir et','siktirgit','siktir git','siktirir','siktiririm','siktiriyor','siktir lan','siktirolgit','siktir ol git','sittimin','sittir','skcem','skecem','skem','sker','skerim','skerm','skeyim','skiim','skik','skim','skime','skmek','sksin','sksn','sksz','sktiimin','sktrr','skyim','slaleni','sokam','sokar\u0131m','sokarim','sokarm','sokarmkoduumun','sokay\u0131m','sokaym','sokiim','soktu\u011fumunun','sokuk','sokum','soku\u015f','sokuyum','soxum','sulaleni','s\u00fclaleni','s\u00fclalenizi','s\u00fcrt\u00fck','\u015ferefsiz','\u015f\u0131ll\u0131k','taaklarn','taaklarna','tarrakimin','tasak','tassak','ta\u015fak','ta\u015f\u015fak','tipini s.k','tipinizi s.keyim','tiyniyat','toplarm','topsun','toto\u015f','vajina','vajinan\u0131','veled','veledizina','veled i zina','verdiimin','weled','weledizina','whore','xikeyim','yaaraaa','yalama','yalar\u0131m','yalarun','yaraaam','yarak','yaraks\u0131z','yaraktr','yaram','yaraminbasi','yaramn','yararmorospunun','yarra','yarraaaa','yarraak','yarraam','yarraam\u0131','yarragi','yarragimi','yarragina','yarragindan','yarragm','yarra\u011f','yarra\u011f\u0131m','yarra\u011f\u0131m\u0131','yarraimin','yarrak','yarram','yarramin','yarraminba\u015f\u0131','yarramn','yarran','yarrana','yarrrak','yavak','yav\u015f','yav\u015fak','yav\u015fakt\u0131r','yavu\u015fak','y\u0131l\u0131\u015f\u0131k','yilisik','yogurtlayam','yo\u011furtlayam','yrrak','zibidi','zigsin','zikeyim','zikiiim','zikiim','zikik','zikim','ziksiiin','ziksiin','zulliyetini','zviyetini'];if (array.some(Word => msgcontent.toLowerCase().includes(Word)))result = true;
    return result;
}
  
client.cache = {
    messages: []
};

async function Spam(message) {
    let result = false;
    const currentmsg = {
        messageID: message.id,
        guildID: message.guild.id,
        authorID: message.author.id,
        channelID: message.channel.id,
        sentTimestamp: message.createdTimestamp
    };
    client.cache.messages.push(currentmsg);

    const spammessage = client.cache.messages.filter((db) => db.authorID === message.author.id && db.guildID === message.guild.id);
    const spamamount = spammessage.filter((db) => db.sentTimestamp > (Date.now() - 2000));
    if(spamamount.length >= 4){await reset(); return result = true; }
    return result;
}

function reset () {
    client.cache = {
        messages: []
    };}


module.exports = exports = { Spam, BadWord, WhiteList, Punish };   